(function (root) {
  'use strict';
  const M = typeof module !== 'undefined' && module.exports ? require('./minigames.js') : root.BunriMinigames;
  const C = M.challenges;
  const e = s => String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const button = (action, value, label, cls = '', attrs = '') => `<button type="button" class="mini-button ${cls}" id="mini-${action}-${value}" data-mini-action="${action}" data-mini-value="${value}" ${attrs}>${label}</button>`;
  function board(game) {
    const p = M.puzzle(game);
    if (game.kind === 'bits') return `<p class="mini-instruction">ONにした重みを足して、目標の数字にしよう。</p><div class="mini-target"><small>届ける数字</small><strong>${p.clue ? "？" : p.value}</strong>${p.clue ? `<span class="bit-clue">${e(p.clue)}</span>` : ""}</div><div class="bit-bank">${p.weights.map((w,i) => button('bit', i, `<small>${w}の位</small><b>${game.bits[i] ? '1' : '0'}</b><span>${game.bits[i] ? 'ON' : 'OFF'}</span>`, `bit-switch ${game.bits[i] ? 'on' : ''}`, `aria-pressed="${game.bits[i]}" aria-label="${w}の位 ${game.bits[i] ? 'ON' : 'OFF'}"`)).join('')}</div>${game.courseId === "junior" && !p.clue ? `<p class="mini-equation">今の合計：<strong>${p.weights.reduce((n,w,i) => n + (game.bits[i] ? w : 0), 0)}</strong></p>` : `<p class="mini-equation">合計を考えてから「確かめる」を押そう。</p>`}`;
    if (game.kind === 'memory') return `<p class="mini-instruction">2枚ずつめくり、符号と文字のペアを6組見つけよう。</p><p class="cipher-key" aria-label="この手紙だけの符号表">${p.pairs.map(pair => `<span>${pair.map(e).join(' ↔ ')}</span>`).join('')}</p><div class="memory-grid">${game.cards.map((card,i) => { const matched = game.matched.includes(card.id), shown = matched || game.revealed.includes(i) || game.showHint; return button('card', i, `<span>${shown ? e(card.label) : '✦'}</span><small>${matched ? 'そろった' : shown ? 'めくったカード' : String(i+1).padStart(2,'0')}</small>`, `memory-card ${shown ? 'revealed' : ''} ${matched ? 'matched' : ''}`, `aria-label="カード${i+1} ${shown ? e(card.label) : '裏向き'}" ${matched ? 'disabled' : ''}`); }).join('')}</div><p class="mini-equation">そろったペア：${game.matched.length} / 6</p>`;
    if (game.kind === 'logic') return `<p class="mini-instruction">${e(p.title)}。<strong>すべての出力条件</strong>を同時に満たそう。</p><ul class="logic-conditions">${p.checks.map(c => `<li><span>${e(c.label)}</span><code>${e(c.formula)}</code><strong>目標 ${c.target ? 'ON' : 'OFF'}</strong>${game.checked ? `<small>${c.evaluate(game.switches) === c.target ? '✓ 達成' : '未達成'}</small>` : ''}</li>`).join('')}</ul><p class="logic-guide">AND＝両方 ／ OR＝どちらか以上 ／ NOT＝反転 ／ XOR＝片方だけ</p><div class="logic-switches">${p.labels.map((label,i) => button('switch', i, `<span>${e(label)}</span><b>${game.switches[i] ? 'ON' : 'OFF'}</b><small>${p.locked.includes(i) ? '固定' : '初期：'+(p.initial[i] ? 'ON' : 'OFF')}</small>`, game.switches[i] ? 'on' : '', `aria-pressed="${game.switches[i]}" ${p.locked.includes(i) ? 'disabled' : ''}`)).join('')}</div><p class="mini-equation">初期状態からの変更：<strong>${C.changes(p,game.switches)} / ${p.maxChanges}個まで</strong><br><small>出力は「確かめる」で判定。クリック回数ではなく、初期状態との違いを数えます。</small></p>`;
    if (game.kind === 'route') return `<p class="mini-instruction"><strong>出発 → 中継A → 中継B → 宛先</strong>の順で、コスト <strong>${p.budget}以下</strong>の経路を作ろう。上下左右に進めます。同じマスは2度通れません。</p><p class="route-legend">マス内の数字＝入るときのコスト。出発は0、宛先も1かかります。</p><div class="route-grid" aria-label="5行5列の通信経路">${Array.from({length:25},(_,i) => { const blocked = p.blocked.includes(i), active = game.path.includes(i), end = i === game.path.at(-1), relay = p.relays.indexOf(i), cost = i === 0 ? 0 : (p.costs[i] || 1); const name = i === 0 ? '出発' : i === 24 ? '宛先' : relay >= 0 ? '中継'+('AB'[relay]) : blocked ? '×' : end ? '●' : active ? '•' : ''; return button('cell', i, `<span>${name}</span>${blocked ? '' : `<small>${cost}</small>`}`, `route-cell ${active ? 'active' : ''} ${end ? 'current' : ''} ${cost > 1 ? 'costly' : ''}`, `aria-label="${Math.floor(i/5)+1}行${i%5+1}列 ${blocked ? '通行不可' : `${name} コスト${cost}${active ? ' 接続済み' : ''}`}" ${blocked || active ? 'disabled' : ''}`); }).join('')}</div><p class="mini-equation ${C.routeCost(p,game.path)>p.budget ? 'over-budget' : ''}">コスト：<strong>${C.routeCost(p,game.path)} / ${p.budget}</strong> ／ A：${game.path.includes(p.relays[0]) ? '通過' : '未通過'} ／ B：${game.path.includes(p.relays[1]) ? '通過' : '未通過'}</p>`;
    if (game.kind === 'median') return `<p class="mini-instruction"><strong>${e(p.title)}</strong><br>${e(p.task)}</p><div class="data-samples" aria-label="観測値、単位${p.unit}">${p.values.map(v => `<span>${v}<small>${p.unit}</small></span>`).join('')}</div>${game.analyzed ? `<p class="stat-confirmed">${C.metrics[p.metric]}：${p.answer}${p.unit} ✓</p><h3 class="mini-step">最後に、その指標を選ぶ理由は？</h3><div class="stat-reasons">${p.reasons.map((r,i) => button('reason', i, e(r))).join('')}</div>` : `<h3 class="mini-step">1. 目的に合う代表値を選ぶ</h3><div class="stat-metrics">${C.metrics.map((name,i) => button('metric', i, e(name), game.metric===i ? 'on' : '', `aria-pressed="${game.metric===i}"`)).join('')}</div><h3 class="mini-step">2. 計算した値を選ぶ</h3><div class="stat-estimates">${p.estimates.map((value,i) => button('estimate', i, `${value}<small>${p.unit}</small>`, game.estimate===i ? 'on' : '', `aria-pressed="${game.estimate===i}"`)).join('')}</div>`}`;
    const values = p.steps;
    return `<p class="mini-instruction">${e(p.title)}。前の作業を終えてからできる順に、カードを押そう。</p><ol class="order-slots">${values.map((_,i) => `<li>${game.order[i] === undefined ? `<span class="slot-placeholder">${i+1}</span>` : e(values[game.order[i]])}</li>`).join('')}</ol><div class="order-bank">${game.bankOrder.map(i => button('pick', i, e(values[i]), '', game.order.includes(i) ? 'disabled' : '')).join('')}</div>`;
  }
  function render(game, result) {
    const cfg = M.config(game.key), cleared = game.status === 'round-clear';
    let body;
    if (result) body = `<div class="mini-result"><span class="mini-seal" aria-hidden="true">${result.assisted ? '◇' : '✦'}</span><h3>${result.assisted ? 'お手本と一緒に、学びを持ち帰ろう。' : 'すべてのミッション、クリア！'}</h3><p class="mini-reward">${e(cfg.reward)}</p><p>${e(cfg.lesson)}</p>${result.assisted ? `<pre class="mini-solution">${e(M.solution(game))}</pre>` : `<p class="mini-stats">チャレンジ ${game.attempts}回 ／ ヒント ${game.hints}回</p>`}<button class="primary-button" id="continue-mini">二人の物語へ戻る →</button></div>`;
    else body = `${board(game)}<p class="mini-message ${cleared ? 'success' : ''}" role="status">${e(game.message)}</p>${game.showHint ? `<p class="mini-hint">${e(M.hint(game))}</p>` : ''}<div class="mini-controls">${cleared ? button('next', '', game.round+1 === M.total(game) ? '結果を見る →' : '次のミッション →', 'primary-button') : `${['bits','logic','sequence','median'].includes(game.kind) && !game.analyzed ? button('check', '', game.kind === 'sequence' ? 'この手順で実行' : '確かめる', 'primary-button') : ''}${['sequence','route'].includes(game.kind) && !game.analyzed ? button('undo', '', '一つ戻す') : ''}${button('hint', '', game.showHint ? 'ヒントを閉じる' : 'ヒントを見る', '', `aria-expanded="${game.showHint}"`)}${button('reset', '', 'この面をやり直す')}</div><button class="text-button mini-assist" id="mini-assist">お手本を見て物語へ進む</button>`}`;
    return `<section class="choice-panel mini-panel" aria-labelledby="mini-title"><div class="mini-heading"><span class="eyebrow">${game.key.startsWith("adult:") ? "CHALLENGE / 成年向け" : "BASIC / 未成年向け"}</span><span>${result ? 'RESULT' : game.kind === 'memory' ? '6 PAIRS' : `${game.round+1} / ${M.total(game)}`}</span></div><h2 id="mini-title" tabindex="-1">${e(cfg.title)}</h2><p class="mini-subtitle">${e(cfg.subtitle)}</p>${body}</section>`;
  }
  const api = { render };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.BunriMinigameUI = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
